import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import {
  AlertTriangle, ArrowRight, Check, ChevronDown, CircleDot, ExternalLink,
  FileSearch, Github, LockKeyhole, Play, RefreshCw, ShieldCheck, TestTube2,
} from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { githubService } from "@/services/githubService";
import type { GitHubReviewFinding, GitHubReviewSeverity } from "@/types";

const severityStyles: Record<GitHubReviewSeverity, { label: string; variant: "destructive" | "warning" | "default" | "muted" }> = {
  critical: { label: "Critical", variant: "destructive" },
  high: { label: "High", variant: "destructive" },
  medium: { label: "Medium", variant: "warning" },
  low: { label: "Low", variant: "muted" },
};

const categoryIcons = { Security: ShieldCheck, Bugs: AlertTriangle, Quality: FileSearch, Testing: TestTube2, Dependencies: CircleDot };
const findingCategories = ["Security", "Bugs", "Quality", "Testing", "Dependencies"] as const;

export default function GitHub() {
  const [repositoryUrl, setRepositoryUrl] = useState("");
  const [branch, setBranch] = useState("main");
  const [scope, setScope] = useState("full");
  const { token } = useAuth();
  const reviewMutation = useMutation({
    mutationFn: (url: string) => githubService.evaluateRepository({ repositoryUrl: url, token }),
  });
  const review = reviewMutation.data;

  function runReview(event: React.FormEvent) {
    event.preventDefault();
    reviewMutation.mutate(repositoryUrl);
  }

  const findingsByCategory = review?.findings.reduce<Record<string, GitHubReviewFinding[]>>((groups, finding) => {
    (groups[finding.category] ??= []).push(finding);
    return groups;
  }, {}) ?? {};

  return (
    <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
        <div>
          <div className="mb-2 flex items-center gap-2 text-sm text-muted-foreground"><Github className="h-4 w-4" /> Engineering intelligence</div>
          <h1 className="text-2xl font-semibold tracking-tight">GitHub repository review</h1>
          <p className="mt-1 max-w-2xl text-sm text-muted-foreground">Submit a public GitHub repository. Findings will be generated by the backend review worker.</p>
        </div>
        <Badge variant="success" className="w-fit"><CircleDot className="h-3 w-3" /> Agent ready</Badge>
      </div>

      <Card className="border-primary/20 bg-primary/[0.03] p-5">
        <form onSubmit={runReview} className="space-y-4">
          <div className="flex items-center gap-2 text-sm font-medium"><Github className="h-4 w-4" /> Repository to evaluate</div>
          <div className="flex flex-col gap-3 lg:flex-row">
            <div className="relative flex-1">
              <ExternalLink className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input value={repositoryUrl} onChange={(event) => setRepositoryUrl(event.target.value)} placeholder="https://github.com/owner/repository" className="pl-9" aria-label="GitHub repository URL" />
            </div>
            <Button type="submit" disabled={reviewMutation.isPending || !repositoryUrl.trim()} className="lg:min-w-36">
              {reviewMutation.isPending ? <RefreshCw className="animate-spin" /> : <Play />}
              {reviewMutation.isPending ? "Checking..." : "Check repository"}
            </Button>
          </div>
          <div className="flex flex-wrap gap-3 text-xs text-muted-foreground">
            <label className="flex items-center gap-2"><span>Branch</span><span className="relative">
              <select value={branch} onChange={(event) => setBranch(event.target.value)} className="h-8 appearance-none rounded-md border border-input bg-background px-3 pr-8 text-foreground"><option>main</option><option>develop</option><option>master</option></select>
              <ChevronDown className="pointer-events-none absolute right-2 top-2 h-3.5 w-3.5" />
            </span></label>
            <label className="flex items-center gap-2"><span>Scope</span><span className="relative">
              <select value={scope} onChange={(event) => setScope(event.target.value)} className="h-8 appearance-none rounded-md border border-input bg-background px-3 pr-8 text-foreground"><option value="full">Full repository</option><option value="security">Security only</option><option value="quality">Quality only</option></select>
              <ChevronDown className="pointer-events-none absolute right-2 top-2 h-3.5 w-3.5" />
            </span></label>
            <span className="flex items-center gap-1.5 py-1.5"><LockKeyhole className="h-3.5 w-3.5" /> Public repositories only</span>
          </div>
        </form>
      </Card>

      {reviewMutation.isError && <div className="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{reviewMutation.error instanceof Error ? reviewMutation.error.message : "Could not verify this GitHub repository."}</div>}

      {review && (
        <>
          <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center">
            <div>
              <div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{review.repositoryName}</h2><Badge variant="outline">{branch}</Badge><Badge variant="success"><Check className="h-3 w-3" /> Repository verified</Badge></div>
              <p className="mt-1 text-xs text-muted-foreground">Findings are waiting for backend worker results · {scope === "full" ? "Full repository" : `${scope} scope`}</p>
            </div>
            <Button variant="outline" size="sm" onClick={() => reviewMutation.mutate(repositoryUrl)}><RefreshCw /> Check again</Button>
          </div>

          <Card className="p-5">
            <div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">Findings</h2><p className="mt-1 text-xs text-muted-foreground">Security, bugs, quality, testing, and dependency findings will appear here.</p></div><Badge variant="outline">{review.findings.length} findings</Badge></div>
            <div className="mt-5 grid gap-3 md:grid-cols-2">
              {findingCategories.map((category) => {
                const Icon = categoryIcons[category];
                const findings = findingsByCategory[category] ?? [];
                return (
                  <section key={category} className="rounded-md border border-border p-4">
                    <div className="flex items-center gap-2 text-sm font-medium"><Icon className="h-4 w-4 text-muted-foreground" /> {category}</div>
                    {findings.length === 0 ? <p className="mt-3 text-xs text-muted-foreground">No findings yet.</p> : (
                      <div className="mt-3 space-y-2">{findings.map((finding) => (
                        <div key={finding.id} className="rounded-md border border-border p-3">
                          <div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{finding.title}</p><p className="mt-1 text-xs text-muted-foreground">{finding.location}</p></div><Badge variant={severityStyles[finding.severity].variant}>{severityStyles[finding.severity].label}</Badge></div>
                          <p className="mt-3 text-sm leading-6 text-muted-foreground">{finding.summary}</p>
                          <div className="mt-3 flex gap-2 border-t border-border pt-3 text-xs"><ArrowRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" /><span><span className="font-medium text-foreground">Recommendation:</span> {finding.recommendation}</span></div>
                        </div>
                      ))}</div>
                    )}
                  </section>
                );
              })}
            </div>
          </Card>
        </>
      )}
    </div>
  );
}
